# Don't change this! Version used to track needed updates.
version = 0
enderPearlTrail = true
snowballTrailDensity = 0.5
allayMagicDensity = 0.2
vexMagicDensity = 0.2
sheepShearFluff = true
improvedDragonFireballTrail = true
commandBlockMinecartParticles = "ON"
endCrystalParticles = true
minecartSparksDisplayType = "DEFAULT"
minecartSparksDensity = 0.5
slimeTrails = true
magmaCubeTrails = true
replaceSlimeSquishParticles = true
replaceOozingEffectParticles = true
replaceSpellCasterParticles = true
ironGolemCrackParticles = true
spectralArrowParticles = true
wardenDeathSoulParticles = true
xpBottleParticlesDisplayType = "DEFAULT"
xpBottleParticlesDensity = 10
eggSmashSoundVolume = 0.5
freezingSnowFlakes = true

[attacked]
chickenFeathers = true
parrotFeathers = true
snowGolemSnowflakes = true

[sleeping]
playerSnoreChance = 0.0
playerSnoreSoundVolume = 0.0
playersHaveSleepingZs = true
villagerSnoreChance = 1.0
villagerSnoreSoundVolume = 0.0
villagersHaveSleepingZs = false
foxesHaveSleepingZs = true
batsHaveSleepingZs = true
catsHaveSleepingZs = true
otherMobsHaveSleepingZs = true
displaySleepingZsOnlyWhenSnoring = false
adjustNameTagWhenSleeping = true

[humanoids]
drowningBubblesDisplayType = "DEFAULT"
drowningBubblesDensity = 10
drowningBubbleAlpha = 1.0
potionRingsDisplayType = "DEFAULT"
potionRingsParticleType = "BOTH"
NPCsHavePotionRings = true

[humanoids.frostyBreath]
displayType = "OFF"
alpha = 0.5
waitTime = 60
seasons = "DEFAULT"
additionalBiomes = [  ]

[humanoids.player]
stomachGrowlingThreshold = 6
stomachGrowlingVolume = 1.0
stomachGrowlingWaitTime = 15
heartBeatingThreshold = 6
heartbeatVolume = 0.0
heartBeatingWaitTime = 3

[dustClouds]
scale = 1.0
alpha = 0.49901962
preventWhenRaining = false
flyIntoWall = true
lessViewBlocking = false
playerFell = true
mobFell = true
landMaceAttack = true
playerRunning = false
mobRunning = true
playerRunningRequiresSpeed = false

[burning]
smoke = "DEFAULT"
flames = true
sparks = true
sounds = true
extinguishSteam = true

[itemRarity]
particlesDisplayType = "NOT_COMMON"
particleColorType = "RARITY_COLOR"
mixedColorName = true
useItemBorder = true
colorOverrides = [  ]
particleMaxHeight = 1.0
particleMaxSpeed = 1.0
particleDensity = 1.0

[explosives]
tntUpdateSmoke = true
tntFlamesDensity = 1
tntSparks = true
creeperSmoke = "UPDATED"
creeperSparks = true